spring.application.name=SpringBotTGmy

bot.name=SpringBot
bot.token=7416418048:AAHzdr2Q8DwujbluRD-UcamMQKMJEwI6xkc


#database
spring.datasource.url=jdbc:mysql://localhost:3306/Bot_db
spring.datasource.username=root
spring.datasource.password=11111111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
